# Generated by Django 5.2.7 on 2025-10-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_tasks_admin_alter_tasks_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='worked_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
