# Generated by Django 5.2.7 on 2025-10-09 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_tasks_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
