# Generated by Django 5.2.7 on 2025-10-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_tasks_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='completion_report',
            field=models.TextField(blank=True, null=True),
        ),
    ]
